-- Developer accounts for sabbpe.com (sign up, email verification, login).
-- MariaDB / MySQL. Run once on the database that DATABASE_URL points to.

-- A sign-up starts here with just an email. Once the link is opened and a password is chosen, it moves
-- into `developers`. No password is stored until then.
create table if not exists pending_signups (
  id                    char(36)     not null primary key,   -- UUID, generated by the app
  email                 varchar(255) not null,               -- stored in lower case
  verify_token_hash     char(64)     not null,               -- SHA-256 of the emailed token
  verify_token_expires  datetime     not null,
  created_at            datetime     not null default current_timestamp,
  unique key pending_signups_email_uniq (email),
  key pending_signups_token_idx (verify_token_hash)
) engine=InnoDB default charset=utf8mb4;

-- Confirmed accounts. Only a verified sign-up is ever inserted here.
create table if not exists developers (
  id                    char(36)     not null primary key,   -- UUID, generated by the app
  email                 varchar(255) not null,               -- stored in lower case
  password_hash         varchar(255) not null,               -- scrypt hash, never the password
  name                  varchar(80)  null,
  verified_at           datetime     null,                   -- set when the email link is opened
  created_at            datetime     not null default current_timestamp,
  last_login_at         datetime     null,
  uat_credentials       json         null,                   -- per-developer UAT credentials (see the docs /docs/uat)
  unique key developers_email_uniq (email)
) engine=InnoDB default charset=utf8mb4;
